apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-cee-admins-cluster
rules:
# CEE can create project using 'oc new-project'
- apiGroups:
  - project.openshift.io
  resources:
  - projectrequests
  verbs:
  - create
