apiVersion: rbac.authorization.k8s.io/v1
aggregationRule:
  clusterRoleSelectors:
    # aggregate all "view" scope rbac
    - matchExpressions:
        - key: rbac.authorization.k8s.io/aggregate-to-view
          operator: In
          values:
            - "true"
    - matchExpressions:
        - key: managed.openshift.io/aggregate-to-backplane-cssre
          operator: In
          values:
            - "true"
kind: ClusterRole
metadata:
  name: backplane-cssre-readers-cluster
rules: []
