# a general "reader" / "view" clusterrole that adds a few things we want to grant to any reader on the cluster such as devaccess and dedicated-readers (see labels used for aggregation)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    managed.openshift.io/aggregate-to-dedicated-readers: "true"
    managed.openshift.io/aggregate-to-devaccess: "true"
    managed.openshift.io/aggregate-to-backplane-cee: "true"
    managed.openshift.io/aggregate-to-backplane-cssre: "true"
    managed.openshift.io/aggregate-to-backplane-srep: "true"
  name: osd-readers-aggregate
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - nodes
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - quota.openshift.io
  attributeRestrictions: null
  resources:
  - clusterresourcequotas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - authorization.openshift.io
  attributeRestrictions: null
  resources:
  - clusterpolicybindings
  verbs:
  - get
  - list
### START - run `oc adm top pod` or `oc adm top node`
- apiGroups:
  - metrics.k8s.io
  resources:
  - nodes
  - pods
  verbs:
  - list
### END
### Start - fix `oc describe nodes`
# https://issues.redhat.com/browse/OHSS-1105
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
### END
### Start - Allow read permissions to more resources
# https://issues.redhat.com/browse/OSD-5537
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectaccessreviews
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.openshift.io
  resources:
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.openshift.io
  resources:
  - clusterroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.openshift.io
  resources:
  - resourceaccessreviews
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.openshift.io
  resources:
  - subjectaccessreviews
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.openshift.io
  resources:
  - clusterautoscalers
  verbs:
  - get
  - list
  - watch
# access resources like oauth, clusterversion,clusteroperators
- apiGroups:
  - config.openshift.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
# access resources like consolelinks, consolenotifications
- apiGroups:
  - console.openshift.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
# access resources flowschemas and prioritylevelconfigurations
- apiGroups:
  - flowcontrol.apiserver.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - image.openshift.io
  resources:
  - images
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - image.openshift.io
  resources:
  - imagesignatures
  verbs:
  - get
  - list
  - watch
# access configs and imagepruners
- apiGroups:
  - imageregistry.operator.openshift.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
# access resources like machineconfigs, machineconfigpods, kubeletconfigs
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal3.io
  resources:
  - provisionings
  verbs:
  - get
  - list
  - watch
# access to storagestates and storageversionmigrations
- apiGroups:
  - migration.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.openshift.io
  resources:
  - clusternetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.openshift.io
  resources:
  - hostsubnets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.openshift.io
  resources:
  - netnamespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - node.k8s.io
  resources:
  - runtimeclasses
  verbs:
  - get
  - list
  - watch
# Access to resources like oauthaccesstokens, oauthauthorizetokens, oauthclients etc
- apiGroups:
  - oauth.openshift.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
# Access to resources like etcds, networks, openshiftapiservers, kubeapiservers etc
- apiGroups:
  - operator.openshift.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - project.openshift.io
  resources:
  - projectrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - samples.operator.openshift.io
  resources:
  - configs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.openshift.io
  resources:
  - rangeallocations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotcontents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotclasses
  verbs:
  - get
  - list
  - watch
# Access to resources like csinodes, csidrivers, volumeattachments etc
- apiGroups:
  - storage.k8s.io
  resources:
  - volumesnapshotclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - template.openshift.io
  resources:
  - brokertemplateinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - user.openshift.io
  resources:
  - groups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - user.openshift.io
  resources:
  - identities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - user.openshift.io
  resources:
  - users
  verbs:
  - get
  - list
  - watch
### End
